### ISSUE TITLE
Viewer links to SDSS files that don't exist and never will

### ISSUE THREAD

**Issue by weaverba137** [legacysurvey/imagine#21]
This issue was originally reported to the SDSS help desk.   Users were interested in images of this galaxy: http://www.legacysurvey.org/viewer?ra=37.5450&dec=-0.6484&zoom=15&layer=sdss2.  When you visit http://www.legacysurvey.org/viewer/data-for-radec/?ra=37.5504&dec=-0.6449&layer=sdss2, it gives a list of SDSS frames that overlap the position.  However, the list includes run numbers that were never processed, such as run 4240 and 4263.  Those runs only exist as unprocessed raw data, so the links provided to the corrected frame images don't exist and never will.  If these runs were never processed in any data release, then there is probably a good reason for that.

**Comment by weaverba137** [comment]
I no longer see the unprocessed run numbers, so maybe this has been fixed?  When was the last time these issues were reviewed in general?

Note that 4263 may have been a typo in the original report.  That does appear to be a valid, processed run.  4240 is gone.

**Comment by dstndstn** [comment]
Thanks for following up.  The list of SDSS fields comes from a file that I generated from the window_flist.fits file, but I honestly cannot find any notes on exactly what commands were run to do so.  It has the same number of rows as the window_flist for DR14, and there's a cut in the viewer code to rerun==301.  Not a very satifying answer, but the problem does seem to be gone.

**Comment by weaverba137** [comment]
The `rerun==301` is probably what did the trick, and checking against window_flist is also a good sign.
