### ISSUE TITLE
Ability to add a crosshair or similar

### ISSUE THREAD

**Issue by tdwelly** [legacysurvey/imagine#72]
A really handy enhancement to this already extremely useful tool would be the ability to request (via URL argument) a cross-hair (or similar) marker to be added to the viewer, that indicates a single location as specified in the URL.

I guess that one could do this already via the catalog upload method but that seems like overkill. It would be much nicer to be able to arrive at the legacy viewer page via an URL formed like:  "http://legacysurvey.org/viewer/?ra=123.456&dec=12.345&layer=dr8&zoom=16&marker_type={type}&marker_ra=123.456789&marker_dec=12.345678", where {type} is one of a small set of shape options.

This would enable a specific galaxy/star/blank-sky position to be highlighted, and would improve the ability to visually compare object positions across image layers.  

A simpler version of this enhancement would be to allow the user to toggle a marker at the centre of the requested image by supplying a single boolean parameter to the URL, e.g. "?marker=true".

Many thanks,
Tom

**Comment by dstndstn** [comment]
"&mark=RA,DEC" already exists.

There's no option for setting the size/type/color etc though.

http://legacysurvey.org/viewer-dev/?ra=293.906&dec=64.627&mark=293.9,64.63

**Comment by tdwelly** [comment]
Ah ok, that's already pretty useful, thanks!

**Comment by weaverba137** [comment]
However, `mark` does *not* exist for the JPEG cutout service:

* http://legacysurvey.org/viewer/jpeg-cutout?ra=293.906&dec=64.627&zoom=13&layer=dr8&mark=293.906,64.627
* http://legacysurvey.org/viewer-dev/jpeg-cutout?ra=293.906&dec=64.627&zoom=13&layer=dr8&mark=293.906,64.627

**Comment by dstndstn** [comment]
Correct, `mark` is done by the browser, not by the rendering engine.
