### ISSUE TITLE
can't access legacysurvey.org

### ISSUE THREAD

**Issue by Amarchuk** [legacysurvey/imagine#75]
Hi,

I can't access the site pages yesterday and today, try different browsers and with/without VPN. Will this be resolved soon? 

Thanks in advance

P.S. Is there is a place where I can monitor related news (e.g. technical work and server shutdown)?

**Comment by djschlegel** [comment]
Expect a return to service some time this weekend: https://nersc-status.lbl.gov/ .  There's some functionality on this Viewer mirror: http://viewer.legacysurvey.org .  Sorry!

**Comment by Amarchuk** [comment]
Thanks a lot for the links and info

**Comment by Amarchuk** [comment]
Hi,

I decide not to open the new one, just comment on existed. Me and my colleagues can access the viewer, but model and residual layers are not loading (both for DR8 & DR9). As far as I can see there is no specific error in Chrome's Dev Console, and the issue persists in Firefox too. Could you please elaborate on that? Thanks!

**Comment by Amarchuk** [comment]
Update: now everything is ok again (but it actually happen time to time. Maybe some db update?)
