### ISSUE TITLE
Cross-site loading errors

### ISSUE THREAD

**Issue by weaverba137** [legacysurvey/imagine#76]
The [prospect](https://github.com/desihub/prospect) viewer uses the jpeg-cutout service, but lately, we have been seeing errors like this in the JavaScript console:

![warning_http_dr8](https://user-images.githubusercontent.com/3780690/104615942-fdc24980-5646-11eb-9351-80096ba0f95d.png)

Obviously we need to change the links we use on the client side to https. I know the cross-site errors *can* be fixed but that has to be fixed on the server side.

This is urgent because modern browsers are being proactive about prohibiting links with errors like this, so it might not be long before the cutout service is entirely unusable.

CC: @armengau

**Comment by dstndstn** [comment]
Ahh, yes, can you try now?  I just added the CORS headers to the viewer/ URLs.  (It was already in the viewer-dev ones)

**Comment by weaverba137** [comment]
Thanks, we'll test that ASAP.

**Comment by armengau** [comment]
@dstndstn Thanks, well as of now I cannot see the change:

- SLL errors when trying to load a jpeg-cutout with https : with both viewer and viewer-dev. The jpeg-cutout is never loaded.

- Using http requests (which I understand we shouldn't):

1. console.log always says [Error] Failed to load resource: Cross-origin redirection to https://www.legacysurvey.org/viewer-dev/jpeg-cutout?ra=214.371272&dec=51.853672&zoom=13&layer=lss-dr9 denied by Cross-Origin Resource Sharing policy: Origin https://jupyter.nersc.gov is not allowed by Access-Control-Allow-Origin. (jpeg-cutout, line 0)
2. Sometimes the jpeg-cutoff is still allowed to be displayed, sometimes not, it seems to be somewhat random, independent of using viewer or viewer-dev.

**Comment by dstndstn** [comment]
You have a typo in the URL above -- `layer=lss-dr9`  should be   `layer=ls-dr9`

**Comment by dstndstn** [comment]
```
> wget -S --header="Origin: https://jupyter.nersc.gov" "https://www.legacysurvey.org/viewer-dev/jpeg-cutout?ra=214.371272&dec=51.853672&zoom=13&layer=ls-dr9"
--2021-01-15 09:41:16--  https://www.legacysurvey.org/viewer-dev/jpeg-cutout?ra=214.371272&dec=51.853672&zoom=13&layer=ls-dr9
Resolving www.legacysurvey.org (www.legacysurvey.org)... 128.55.206.24, 128.55.206.26
Connecting to www.legacysurvey.org (www.legacysurvey.org)|128.55.206.24|:443... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  server: nginx/1.17.2
  date: Fri, 15 Jan 2021 14:41:17 GMT
  content-type: image/jpeg
  content-length: 29795
  expires: Fri, 15 Jan 2021 15:41:17 GMT
  last-modified: Fri, 15 Jan 2021 14:41:17 GMT
  access-control-allow-origin: *
  strict-transport-security: max-age=31536000
Length: 29795 (29K) [image/jpeg]
Saving to: ‘jpeg-cutout?ra=214.371272&dec=51.853672&zoom=13&layer=ls-dr9.6’

jpeg-cutout?ra=214.371272&dec=51.853672& 100%[=================================================================================>]  29.10K  --.-KB/s    in 0.09s

2021-01-15 09:41:17 (334 KB/s) - ‘jpeg-cutout?ra=214.371272&dec=51.853672&zoom=13&layer=ls-dr9.6’ saved [29795/29795]
```

Notice the `access-control-allow-origin: *` in the server response.

**Comment by armengau** [comment]
Thanks for this example !
Indeed the request was http[s]://legacyviewer....
=> switching to https://www.legacyviewer... seems to solve the issues.

I will test extensively to make sure all works.

**Comment by armengau** [comment]
After testing combinations:

- requesting layer-dr8, with https, I don't have any error/warning anymore, good.

- With [ls-]dr9:
1. https://www.legacysurvey.org/viewer-dev/jpeg-cutout?ra=214.371272&dec=51.853672&zoom=13&layer=ls-dr9  >  ok
2. https://www.legacysurvey.org/viewer/jpeg-cutout?ra=214.371272&dec=51.853672&zoom=13&layer=ls-dr9 > OSError at jpeg cutout
3. https://www.legacysurvey.org/viewer[-dev]/jpeg-cutout?ra=214.371272&dec=51.853672&zoom=13&layer=dr9 > no such layer

So the last question is: is it fine to use "viewer-dev" in prospect ? Maybe not on the long run.

**Comment by dstndstn** [comment]
DR9 is not officially released yet (SOON!, we promise), so "viewer" failing
with "ls-dr9" is expected.  And "dr9" failing is expected, because that's
not its name :)

cheers,
--dustin

**Comment by armengau** [comment]
Ok, thanks
Eric

**Comment by dstndstn** [comment]
ls-dr9 is now available in the main "viewer" site.

**Comment by weaverba137** [comment]
@dstndstn, I think this has been fixed for a while now.  Is there any reason it's still open?

**Comment by dstndstn** [comment]
No good reason!
