### ISSUE TITLE
Code License/Credit?

### ISSUE THREAD

**Issue by ryanhausen** [legacysurvey/imagine#81]
Howdy!

I work on a project called [FitsMap](https://github.com/ryanhausen/fitsmap) that also displays astronomical images using leaflet. I came across the legacy viewer and thought the CSS image filters were a great tool to have available. I am working on my own implementation in my code base inspired by what you have done here, but noticed you don't have a license for the code. I want to acknowledge the source of the inspiration in my codebase. 

Would you mind telling me what license the code is under?

Thanks!

Ryan

**Comment by JBorrow** [comment]
I also have this question, we would like to re-use some code for an upcoming Simons Observatory project.

**Comment by TriShotFlurry** [comment]
Yes, try https://www.legacysurvey.org/acknowledgment/

**Comment by dstndstn** [comment]
> @dstndstn any objections to licensing this with the BSD 3-clause license like other DESI code? I see that you released Tractor under GPL but that causes headaches for LBL/UC lawyers, so BSD would be highly preferred (like legacypipe) if possible.

That's just Big Berkeley trying to sell more Berkeley

**Comment by dstndstn** [comment]
Apologies to @ryanhausen and @JBorrow for not noticing/responding to this last year!!

I just added the 3-clause BSD LICENSE file.

**Comment by ryanhausen** [comment]
Great thanks!
